/*
XYO RESTful Transaction Enrichment API

RESTful API for enriching financial transactions.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnrichTransactionsRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrichTransactionsRequestInner{}

// EnrichTransactionsRequestInner struct for EnrichTransactionsRequestInner
type EnrichTransactionsRequestInner struct {
	Content     *string `json:"content,omitempty"`
	CountryCode *string `json:"countryCode,omitempty"`
}

// NewEnrichTransactionsRequestInner instantiates a new EnrichTransactionsRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrichTransactionsRequestInner() *EnrichTransactionsRequestInner {
	this := EnrichTransactionsRequestInner{}
	return &this
}

// NewEnrichTransactionsRequestInnerWithDefaults instantiates a new EnrichTransactionsRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrichTransactionsRequestInnerWithDefaults() *EnrichTransactionsRequestInner {
	this := EnrichTransactionsRequestInner{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *EnrichTransactionsRequestInner) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrichTransactionsRequestInner) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *EnrichTransactionsRequestInner) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *EnrichTransactionsRequestInner) SetContent(v string) {
	o.Content = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *EnrichTransactionsRequestInner) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrichTransactionsRequestInner) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *EnrichTransactionsRequestInner) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *EnrichTransactionsRequestInner) SetCountryCode(v string) {
	o.CountryCode = &v
}

func (o EnrichTransactionsRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrichTransactionsRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	return toSerialize, nil
}

type NullableEnrichTransactionsRequestInner struct {
	value *EnrichTransactionsRequestInner
	isSet bool
}

func (v NullableEnrichTransactionsRequestInner) Get() *EnrichTransactionsRequestInner {
	return v.value
}

func (v *NullableEnrichTransactionsRequestInner) Set(val *EnrichTransactionsRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrichTransactionsRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrichTransactionsRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrichTransactionsRequestInner(val *EnrichTransactionsRequestInner) *NullableEnrichTransactionsRequestInner {
	return &NullableEnrichTransactionsRequestInner{value: val, isSet: true}
}

func (v NullableEnrichTransactionsRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrichTransactionsRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
