name: Unit Tests

on:
  push:
    branches: [ "main", "release-*" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Dockerfiles
      run: make
